cabal-version:      3.0
name:               synth
version:            0.1.0.0
author:             casperrr
category:           Sound
build-type:         Simple

common warnings
    ghc-options: -Wall

executable synth
    import:           warnings
    main-is:          Main.hs
    -- other-modules:
    build-depends:    base ^>=4.18.3.0
    hs-source-dirs:   .
    default-language: Haskell2010
