cabal-version:      3.0
name:               synth
version:            0.1.0.0
author:             casperrr
category:           Sound
build-type:         Simple

executable synth
    main-is:          Main.hs
    other-modules:    Synth
                      Synth.Types
                      Synth.Util
    build-depends:    process ^>=1.6.26.1,
                      base ^>=4.18.3.0,
                      bytestring,
    hs-source-dirs:   .
    default-language: Haskell2010
